[package]
name = "pencil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm = "0.0.1"
llvm-sys = "140.0.2"
